/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_5 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] s,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] operation;
  
  reg [15:0] value;
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        operation = a + b;
      end
      2'h1: begin
        operation = a - b;
      end
      default: begin
        operation = a + b;
      end
    endcase
    value = a - b;
    z = (~|value);
    v = (a[15+0-:1] & (b[15+0-:1] ^ alufn[0+0-:1]) & ~operation[15+0-:1]) | (~a[15+0-:1] & ~(b[15+0-:1] ^ alufn[0+0-:1]) & operation[15+0-:1]);
    n = value[15+0-:1];
    s = operation;
  end
endmodule
