/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module storevalue_3 (
    input clk,
    input buttona,
    input buttonb,
    input [15:0] switches,
    output reg [15:0] geta,
    output reg [15:0] getb
  );
  
  
  
  wire [1-1:0] M_eda_out;
  reg [1-1:0] M_eda_in;
  edge_detector_9 eda (
    .clk(clk),
    .in(M_eda_in),
    .out(M_eda_out)
  );
  wire [1-1:0] M_edb_out;
  reg [1-1:0] M_edb_in;
  edge_detector_9 edb (
    .clk(clk),
    .in(M_edb_in),
    .out(M_edb_out)
  );
  
  wire [1-1:0] M_button_condA_out;
  buttoncon_11 button_condA (
    .clk(clk),
    .in(buttona),
    .out(M_button_condA_out)
  );
  
  wire [1-1:0] M_button_condB_out;
  buttoncon_11 button_condB (
    .clk(clk),
    .in(buttonb),
    .out(M_button_condB_out)
  );
  
  reg [15:0] M_storevalueA_d, M_storevalueA_q = 1'h0;
  
  reg [15:0] M_storevalueB_d, M_storevalueB_q = 1'h0;
  
  always @* begin
    M_storevalueA_d = M_storevalueA_q;
    M_storevalueB_d = M_storevalueB_q;
    
    M_eda_in = M_button_condA_out;
    M_edb_in = M_button_condB_out;
    if (M_eda_out) begin
      M_storevalueA_d = switches;
    end
    if (M_edb_out) begin
      M_storevalueB_d = switches;
    end
    geta = M_storevalueA_q;
    getb = M_storevalueB_q;
  end
  
  always @(posedge clk) begin
    M_storevalueB_q <= M_storevalueB_d;
  end
  
  
  always @(posedge clk) begin
    M_storevalueA_q <= M_storevalueA_d;
  end
  
endmodule
